name: Add issue to ls project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to ls project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/software-mansion/projects/33
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
