name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 2.9.4, 2.10.1, 2.11.4, 2.12.2, 2.13.1, 2.14.0, 2.15.2, 2.16.1, 2.17.0, 2.18.0 ]
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470 # v1.1.0
      - uses: software-mansion/setup-scarb@2a96b748888e3329ee44ac9ac073d930e692b3cd # v1.5.1
        with:
          scarb-version: ${{ matrix.version }}
      - uses: foundry-rs/setup-snfoundry@16e23ddd0e2845f38727c92f4b913a7b728cda9e # v6.0.0
      - run: cargo test --release
        if: matrix.version == '2.9.4' || matrix.version == '2.10.1'
      - run: cargo test --release --features allows-excluding-macros
        if: matrix.version != '2.9.4' && matrix.version != '2.10.1'

  rustfmt:
    name: Check rust formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: cargo fmt --check

  scarbfmt:
    name: Check cairo formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: software-mansion/setup-scarb@2a96b748888e3329ee44ac9ac073d930e692b3cd # v1.5.1
      - run: |
          output=$(find . -type f -name "Scarb.toml" -execdir sh -c '
              echo "Running \"scarb fmt\" in directory: $PWD"
              scarb fmt --check
          ' \;)
          echo "$output"
          if grep -iq "Diff" <<< "$output"; then
              exit 1
          fi
          exit 0

  clippy:
    name: Check linter
    runs-on: ubuntu-latest
    env:
      # Make sure CI fails on all warnings - including Clippy lints.
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: cargo lint

  typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: typos-action
        uses: crate-ci/typos@f8a58b6b53f2279f71eb605f03a4ae4d10608f45 # v1.47.0
