name: Scheduled Tests

on:
  schedule:
    - cron: "0 8 * * 1,4" # Every Monday and Thursday at 08:00 UTC
  workflow_dispatch:

jobs:
  get-latest-release:
    name: Get latest release tag
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Get latest release tag
        id: get-tag
        run: |
          TAG=$(gh release list --repo ${{ github.repository }} --limit 1 --json tagName -q '.[0].tagName')
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Tests (${{ matrix.ref }}, Scarb ${{ matrix.scarb-version }})
    needs: get-latest-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ref:
          - main
          - ${{ needs.get-latest-release.outputs.latest-tag }}
        scarb-version: [latest, nightly]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ matrix.ref }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - uses: hrishikesh-kadam/setup-lcov@6c1aa0cc9e1c02f9f58f01ac599f1064ccc83470 # v1.1.0
      - uses: software-mansion/setup-scarb@2a96b748888e3329ee44ac9ac073d930e692b3cd # v1.5.1
        with:
          scarb-version: ${{ matrix.scarb-version }}
      - uses: foundry-rs/setup-snfoundry@16e23ddd0e2845f38727c92f4b913a7b728cda9e # v6.0.0
      - run: cargo test --release --features allows-excluding-macros

  notify_failed:
    runs-on: ubuntu-latest
    if: always() && failure()
    needs: [test]
    steps:
      - name: Notifying about check fail!
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_SCHEDULED_CHECK_FAILURE_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
